export const GET_COCKTAILS = "GET_COCKTAILS";
export const GET_DRINKS_LOADING = "GET_DRINKS_LOADING";
export const CLEAR_COCKTAILS = "CLEAR_COCKTAILS";
export const GET_DRINKS_ERROR = "GET_DRINKS_ERROR";
